### PR TITLE
feat:pass other apollo server options.

### PR DESCRIPTION
**Pull request by whlsxl**
##### Checklist

- [x] `npm test` passes
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message follows commit guidelines

### CODE REVIEW

**Comment by whlsxl** [comment]
添加了测试 https://github.com/eggjs/egg-graphql/pull/24

**Comment by whlsxl** [comment]
Any update?

**Comment by atian25** [comment]
ping @JasinYip

**Comment by JasinYip** [comment]
@whlsxl 已发布到 v2.7.0 🤩 https://www.npmjs.com/package/egg-graphql/v/2.7.0

**Pull request merged**
