### PR TITLE
feat: Support `schemaDirectives`

### PR DESCRIPTION
**Pull request by Maledong**
1) Ref: https://github.com/eggjs/egg/issues/3063.
2) Update to the latest version of Nodejs (10.X).

- [x] `npm test` passes
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message follows commit guidelines

### CODE REVIEW

**Comment by Maledong** [comment]
@thonatos, @atian25

**Comment by jtyjty99999** [comment]
+1

**Comment by jtyjty99999** [comment]
@Maledong please merge recent master branch

**Comment by Maledong** [comment]
@jtyjty99999 : OK

**Pull request merged**
